- Functions/Public/ConvertTo-HtmlTable.ps1
- Tests/ConvertTo-HtmlTable.Tests.ps1
- pshtml.psd1
I added a parameter where you could pass the properties of the object you want to show up in the module (Inclunding Pester test)
> Issue #19 added parameter for properties

- Functions/Public/body.ps1
The body function is now on v2.0
> updated the body function

- Functions/Public/blockquote.ps1
- Tests/blockquote.tests.ps1
Updated the Blockquote function to v2.0
> Updated Blockquote

- Functions/Public/div.ps1
- Functions/Public/pre.ps1
- Functions/Public/section.ps1
- Tests/Section.Tests.ps1
- Tests/pre.tests.ps1
Updated the pre function to v2.0
Pester Tests passed
> Element pre v2.0.1

- Functions/Public/div.ps1
- Functions/Public/section.ps1
- Tests/Section.Tests.ps1
Updated the div Function to v2
Pester Tests ran through.
> Element div v2.0.1

- Functions/Public/section.ps1
- Tests/Section.Tests.ps1
Updated the sectionFunction to v2
Added Pester Tests and Pester Tests ran through.
> Updated Section function to v2 and added test for Section

- ISSUE_TEMPLATE.md
Added 'simple' ISSUE_TEMPLATE.md
#18
> Added 'simple' ISSUE_TEMPLATE.md

- Functions/Public/base.ps1
- Tests/base.Tests.ps1
Bug fix for Base
Fix base cmdlet
> Fixed base

- Functions/Public/area.ps1
- Functions/Public/body.ps1
- Functions/Public/div.ps1
- Functions/Public/img.ps1
- Functions/Public/optgroup.ps1
- Tests/img.Tests.ps1
- Tests/optgroup.tests.ps1
- pshtml.psd1
> Bugfix failing tests

- PSHTML/Functions/Public/ConvertTo-HtmlTable.ps1
- PSHTML/Functions/Public/a.ps1
- PSHTML/Functions/Public/address.ps1
- PSHTML/Functions/Public/dd.ps1
- PSHTML/Functions/Public/dl.ps1
- PSHTML/Functions/Public/dt.ps1
- PSHTML/Functions/Public/em.ps1
- PSHTML/Functions/Public/fieldset.ps1
- PSHTML/Functions/Public/figcaption.ps1
- PSHTML/Functions/Public/figure.ps1
- PSHTML/Functions/Public/hr.ps1
- PSHTML/Functions/Public/keygen.ps1
- PSHTML/Functions/Public/label.ps1
- PSHTML/Functions/Public/legend.ps1
- PSHTML/Functions/Public/li.ps1
- PSHTML/Functions/Public/meter.ps1
- PSHTML/Functions/Public/nav.ps1
- PSHTML/Functions/Public/ol.ps1
- PSHTML/Functions/Public/pre.ps1
- PSHTML/Functions/Public/progress.ps1
- PSHTML/Functions/Public/section.ps1
- PSHTML/Functions/Public/selecttag.ps1
- PSHTML/Functions/Public/strong.ps1
- PSHTML/Functions/Public/style.ps1
- PSHTML/Functions/Public/textarea.ps1
- PSHTML/Functions/Public/ul.ps1
> Fix Set-HtmlTag position

- hands-on/PSHTMLwithNodeJS.md
- hands-on/PSHTMLwithPowerShell.md
- hands-on/selectTag-UseCase.md
1. Included example for PSHTML with Polaris
2. Shared a tip (Auto populate values for drop down) for selectTag function.
> Added hands-on folder to share real world examples, tips and tricks

- CI/CI_Start.ps1
- PSHTML/Functions/Public/ConvertTo-HtmlTable.ps1
Updated CI
Push to the Gallery
> push psgallery

- appveyor.yml
> push psgallery - Added PSGalleryKey

- CI/CI_Start.ps1
> push psgallery updated CI

- CI/CI_Start.ps1
> push psgallery - fixed CI

- appveyor.yml
It looks like you've got the actual module working, there was just a small bug in the appveyor.yml that was preventing your tests from running, so I've fixed that.
The only tests failing are the vscode snippet tests, which are failing on both Linux and Windows; I think  it's because vscode is not installed on the test machine, so you'd need to get AppVeyor to do that first. I didn't want to add that in this branch because it's a different thing, and I don't want to make it look untidy :)
You will run into problems with $env:appdata on Linux, as it doesn't exist. I *think* the directory you'd need is ~/.config but I'm not 100% certain that that's going to work across all distributions - offering the path parameter as you have done is probably the best choice. …
> Feature linux support

- CONTRIBUTING.md
Change the markdown to fix spelling, lists, headings and other minor edits
> Edit Contributing Guidelines

- Tests/Area.Tests.ps1
- Tests/a.Tests.ps1
- Tests/base.Tests.ps1
- Tests/blockquote.tests.ps1
- Tests/sub.tests.ps1
- Tests/sup.tests.ps1
Add testing function default param and fix some woop to 'woop'
> Pester Add testing default param

- PSHTML/Functions/Public/blockquote.ps1
Modified the way htmltagparams variable is filling.
With this new method, we are sure to have all parameters passed to the function
**AND** defaults parameters (the ones not passed to function)
Resolves #108
Fixes #61
Resolves #50
> New $htmltagparams + fix content

- PSHTML/Snippets/PsHtml_Basic.Snippet.code-snippets
- PSHTML/Snippets/PsHtml_full.Snippet.code-snippets
- Add 2 Vscode Snippets
Resolves #101
> Add 2 Vscode Snippets

- Functions/Public/br.ps1
adding br.ps1 to add the BR tag in HTML documents.
> Adding BR Tag

- Code/Functions/Public/ConvertTo-PSHtmlTable.ps1
resolving issue #210 
Now accepts pipeline input
`get-service | select name,id -first 10 | convertto-pshtmltable -caption "services"`
> Fixing Convertto-pshtmltable

- tagv3Prototype.ps1
> New GetHTML Method

- docs/Charts/Charts.Bar.Md
- docs/Charts/Charts.Doughnut.Md
- docs/Charts/Charts.Pie.Md
- docs/Charts/Charts.Radar.md
- docs/Charts/Charts.md
- docs/_HowToUsePSHTML.md
fixed Bug in Charts documentation, where the linked images aren't displayed
> changed docs to display images

- Change_Log.md
- PSHTML/PSHTML.psd1
Removed Alpha / updated Change log
> Updated module metadata

- CONTRIBUTING.md
- PULL_REQUEST_TEMPLATE.md
I have fixed some English wording, spelling and punctuation in CONTRIBUTING.
> Minor corrections to English documentation

- Code/Functions/Public/a.ps1
Fixes #289 
Added 
[AllowEmptyString()]
[AllowNull()]
to the **href** parameter inside **a** function
> fix a -href '' Throws error #289
